### PR TITLE
Fix duplicate broadcast receiver

### PR DESCRIPTION
**Pull request by gwolf2u**

### CODE REVIEW

**Comment by varund7726** [comment]
Please clean up white spaces .
And I see no broadcast receiver gone . I see only logs which cause major logspam .

**Comment by gwolf2u** [comment]
this is simply based on omnirom commit https://github.com/omnirom/android_packages_apps_OmniSwitch/commit/f0555bf9ac7b56238f3f7b9eadb58504a95d030d 
also fixes "Sending non-protected broadcast org.omnirom.omniswitch.ACTION_TOGGLE_OVERLAY" spamming in log

**Comment by varund7726** [comment]
So where is the authorship?

**Comment by varund7726** [comment]
I see maxwen is the author

**Comment by varund7726** [comment]
again where is the authorship?

**Comment by gwolf2u** [comment]
Not really sure how to set that
However you can close the pull request 
I just wanted to fix an issue I've noticed

**Comment by varund7726** [comment]
i know mate , but we cant merge without proper authorship or we get flagged

**Comment by gwolf2u** [comment]
So how to add authorship anyway?

**Comment by varund7726** [comment]
git commit --amend--aurhor="maxwen"

**Pull request merged**
